### ISSUE TITLE
Pull facility name to enrollment table from kobolink table

### ISSUE THREAD

**Issue by siddhant3030** [DevDataPlatform/dbt_shri#14]
You'll have to pull the facility name for the final table and try to rename the _submitted_by to username in both tables. So that we have a common column to match on. 

1.  Do the join to match and create a facility column in the enrollment form. 
2. rename rootuuid
3. pull data_enrollment from  formtimestampformatted
4.  meta_deprecatedid text to depecratedID
5. calculate age_years from yob and create a new column in the same table. 
6. age_cat from age_years. Put some conditions for multiple age categories.

**Comment by Abhishek-N** [comment]
@siddhant3030 can we close this issue?
