### ISSUE TITLE
Cleaning up the daily status form

### ISSUE THREAD

**Issue by siddhant3030** [DevDataPlatform/dbt_shri#17]
For this, I have shared pynb file named daily status in the data folder. It will give you some info about what raw data looks like and what we want for the dashboard. 

<img width="1001" alt="Screenshot 2023-03-29 at 11 31 05 AM" src="https://user-images.githubusercontent.com/9019958/228440752-989c6e77-01f2-4a3a-9a50-0f1c81e006b5.png">

for these type of fields 
begin_group_b0spfk4xt_passerby_man_number
begin_group_aypvm5n7n_passerby_man_number

we will coalesce and rename it. You can take a look at the data what is mentioned there

**Comment by Abhishek-N** [comment]
Daily status form is a new model? Should I create it by taking data from airbyte?

**Comment by siddhant3030** [comment]
@Abhishek-N Its already there. non_regular_use_tracking_normalized
