### ISSUE TITLE
Issue with Passerby Data

### ISSUE THREAD

**Issue by siddhant3030** [DevDataPlatform/dbt_shri#25]
1. Observation with _id “140619369” is listed in your dataset with facility=Basgoda, but in mine it is Dundibagh. I went back to the original kobo data online and can see that it is dundibagh. Can you figure out why this is the case?

2. I found a few observations in your dataset that have been deleted from the kobo dataset (for example _id “142313295”). How do we do a full fresh pull of all the data?

**Comment by siddhant3030** [comment]
- We will do the join to facility_kobo table to pull the facility name and not use facility which is already there.

**Comment by helenpitchik** [comment]
1. I am getting the date and time from the "starttime" variable, which should be in IST, while I think yours might be in IST? Your dates are sometimes a day later than mine. Possibly from the "_submission_time" variable? 

2. Could you keep a time variable? (call it time_auto) in the data_passerbyuse_clean file?

**Comment by siddhant3030** [comment]
Change submission time to starttime in passerbydata

**Comment by helenpitchik** [comment]
I cross-checked the data again, a couple of observations: 

1. The time stamps seem to not quite be converted to time variables, can you take a look?
2. can you refresh the data from the beginning? (or let me know how to do it)? I updated the facility names in the facility koboID link form but don't see the updates yet

**Comment by siddhant3030** [comment]
select * from intermediate_cleaned.nonregular_use_tracking where _id = '152274509' 

fix the time_auto variable in passerby data

**Comment by helenpitchik** [comment]
A couple of notes: 
1. Can you drop all instances where _submitted_by does not link with a facility name -- this is testing data
2. Can you refresh from the beginning? There are a couple of observations 252765959 and 252765956 that were deleted but are still showing up in the dataset

**Comment by siddhant3030** [comment]
For data passersby, the second point is done. Not sure about the first one.

**Comment by helenpitchik** [comment]
The first point is about the facility to id link. If the id doesn't like to a facility, the observation should be dropped!

**Comment by siddhant3030** [comment]
@helenpitchik this is done

**Comment by siddhant3030** [comment]
for enrollment and barcode we will be doing full refresh.

**Comment by helenpitchik** [comment]
Great, the data looks like it matches for both the full and _reduced versions! I just see a mismatch for the 29th august data, which looks like  it wasn't released yet from your end. This can be closed!

**Comment by siddhant3030** [comment]
thanks
