### ISSUE TITLE
Barcode checkin data

### ISSUE THREAD

**Issue by helenpitchik** [DevDataPlatform/dbt_shri#30]
1. Can you add time to the dataset with the name time_auto? Please use the variable "nametimestampformatted"
2. Can you include the _id variable so I can compare observations easier? We might end up taking it out for the final clean dataset generation, but it would be helpful for now!

**Comment by siddhant3030** [comment]
@helenpitchik  I have added the fix for this. This will be available tomorrow.

**Comment by helenpitchik** [comment]
I've checked the data again, a couple of questions:
1. Can you check the time variable again? it doesn't seem to quite be a time variable yet, I am seeing a string of numbers (for example for _id=197685632 I see time_auto=14148
2. Can you reload all the data from the beginning?

**Comment by siddhant3030** [comment]
Let's discuss this today.

**Comment by helenpitchik** [comment]
A couple of points: 
1. If the _submitted_by userid is not linked to a facility, it is considered testing data and should be dropped from the dataset
2. I am not sure why some of the userids are not valid userids (for example 11600077 from id 251175961). The userid is generated by staff scanning a barcode in the kobocollect app, and the barcode is linked to a prescribed userid. I don't know why a few are coming through that aren't on the barcode. Do you have any idea?

**Comment by siddhant3030** [comment]
@helenpitchik not sure about the second point and how it is not valid. This is also coming in the raw data. Something you should check in Kobo itself

**Comment by siddhant3030** [comment]
select * from prod_final.data_barcode_checkin where facility is null

**Comment by helenpitchik** [comment]
To discuss: Could we have a list of the userids that do not link up that compile on a separate dataset?

**Comment by siddhant3030** [comment]
date_auto, time_auto, facility and userid for user 
select distinct userid, position from intermediate_cleaned.staff_barcode where position is null
