### ISSUE TITLE
KoboToolBox: Pull data from Enrollment form. 

### ISSUE THREAD

**Issue by siddhant3030** [DevDataPlatform/dbt_shri#4]
So for this one, you'll have to pull some amount of data from _airbyte_raw_enrollment table. I've shared the enrollment pynb file in the data folder. 

There will be 3 sets of data. One will be the initial set of transformations that are being done in R. 
which you can see here 
https://github.com/DevDataPlatform/dbt_shri/blob/main/data/Enrollment%20Data.ipynb

Each has starting comments which explain what is that data. and the final result which you want to look at is mentioned in the comments.

**Comment by vinod-rajasekaran** [comment]
#15 adds this
