### ISSUE TITLE
kobotoolbox: Create a new model for Facility KoboID link

### ISSUE THREAD

**Issue by siddhant3030** [DevDataPlatform/dbt_shri#5]
So here you'll have to create a new model with facility form to pull these two fields 
"facilityname": "Basgoda",
"kobo_username": "ranjitkumar" 

and rename this as you will be using this in daily issue form model

**Comment by siddhant3030** [comment]
@Abhishek-N for this again you'll have to resync the data in the airbyte connector. There is a new form which needs to be pulled. You can do this by reset your data button in the airbyte connection

**Comment by vinod-rajasekaran** [comment]
Can we mark as done only after the PR and issues are closed only?
